### ISSUE TITLE
Artifact of War is... insane. in a bad way.

### ISSUE THREAD

**Issue by Darkmega18** [bcs4313/Artifacts-Of-DOOM#3]
Too many items too quickly. too much spawns too fast. my game eventually bogged down at stage two and so the only way I was surviving was cause of the sheer amount of enemies that I was generating barrier off with every hit due to playing the dancer. :V  eventually early next level an alpha construct lasered me to death with gauranteed crit which I tripped into cause my game was a slideshow...

maybe turn it down a little?

**Comment by bcs4313** [comment]
All artifacts have their own settings in the main menu that allow you to adjust them to your liking (settings->mod settings->Artifacts of Doom). This includes Artifact of War, which you can adjust droprates, swarm cap, evolution rates, etc.

I do agree on the merit that its default could be a bit much for new users though. I'll consider toning it down for the next update.

**Comment by Darkmega18** [comment]
What if every time the enemies level up, they gain an item, rather than just giving them a big mass of items all in one go? cause it was kinda nuts how they got so many items right off the bat like that. 

so as the level climbs, their power spike is greater basically and so will continue to scale if you have a mod or a difficulty that allows enemies to get past max quicker.

Something that could also work is that for every minute that you pass staying in the same level the director gets more credits. like a configurable amount of say default 20% more enemies every minutes.

But whenever the player levels up, you also deposit an item onto them. But theres an upper limit on how quickly a player can level which stops it from making them god so much, but possibly helps with the need to rush also.

and if it's war, wouldn't the enemies get angry for you killing them? so on that point, maybe killing an enemy increases the difficulty scaling rate marginally, like say 1%, which would inturn make the enemies evolve quicker. 
this too would decay when you move to a new stage and start again as the enemies regroup again to your new location or something.

**Comment by bcs4313** [comment]
The leveling up to give items is a good idea. It would give a general sense of how fast enemies are earning items. The original reason as to why I had it update on stage change was because of how evolution worked for the enemies. But due to some digging in 2022 I gained access to many more parameters that could give me control over the evolution trigger. I'll see if I can make that change.
- The level cap ideally would be kept, and I would instead have it scale off of level, then time. Or I could just have evolution scale simply off of difficulty ticks, which are infinite.

I'd rather keep the change in item scaling on the change of stage, because it makes levels feel more like a race against time. I could adjust the default parameters of exponential item scaling to make it less ridiculous, which is the plan at the moment for both players and monsters.

**Comment by Darkmega18** [comment]
alright, sounds good. :o
